#!/usr/bin/env python3
"""Generate a starter ``/llms.txt`` for a site.

Seeds from the homepage (site name + description) and discovered pages (from the
sitemap or internal links), fetches each page's title/description, groups them
into sections, and emits an llms.txt-formatted markdown file (see llmstxt.org).

This is a *starting point* to curate, not a finished file — placeholders are
marked ``TODO``. Note: evidence that llms.txt affects AI-search visibility is
still limited; treat it as a low-cost, low-certainty addition (see
references/geo-llmo.md).

Usage:
    python generate_llms.py https://example.com
    python generate_llms.py https://example.com --max-pages 60 -o llms.txt
"""

from __future__ import annotations

import argparse
import os
import sys
from concurrent.futures import ThreadPoolExecutor
from urllib.parse import urljoin, urlparse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from lib import http, htmlx  # noqa: E402
from lib import config as configlib  # noqa: E402
from lib.robots import RobotsTxt  # noqa: E402
import crawl_site  # noqa: E402


def section_for(url: str) -> str:
    """Bucket a URL into an llms.txt section by its path."""
    path = urlparse(url).path.strip("/")
    if not path:
        return "Main"
    parts = path.split("/")
    if len(parts) == 1:  # top-level pages (/about, /contact) share "Main"
        return "Main"
    return parts[0].replace("-", " ").replace("_", " ").strip().title() or "Main"


def group_sections(pages: list) -> list:
    """Group page metas into ordered ``[(section, [pages])]`` (Main first)."""
    buckets: dict = {}
    for p in pages:
        buckets.setdefault(section_for(p["url"]), []).append(p)
    ordered = []
    if "Main" in buckets:
        ordered.append(("Main", buckets.pop("Main")))
    for name in sorted(buckets):
        ordered.append((name, buckets[name]))
    return ordered


def _slug_title(url: str) -> str:
    slug = urlparse(url).path.strip("/").split("/")[-1]
    return slug.replace("-", " ").replace("_", " ").title()


def render_llms_txt(site_name: str, description: str, sections: list) -> str:
    lines = [f"# {site_name or 'TODO: site name'}", ""]
    lines.append(f"> {description or 'TODO: one-sentence description of the site.'}")
    lines.append("")
    lines.append("<!-- Starter llms.txt generated by narwhal — review and curate "
                 "before publishing. Remove pages that are not key entry points. -->")
    lines.append("")
    for name, pages in sections:
        lines.append(f"## {name}")
        lines.append("")
        for p in pages:
            title = p["title"] or _slug_title(p["url"]) or "TODO: page title"
            desc = p["description"].strip()
            suffix = f": {desc}" if desc else ""
            lines.append(f"- [{title}]({p['url']}){suffix}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _page_meta(url, allow_private, timeout):
    resp = http.fetch(url, allow_private=allow_private, timeout=timeout)
    if not resp.ok:
        return None
    doc = htmlx.parse(resp.text, base_url=resp.final_url or url)
    return {"url": resp.final_url or url, "title": doc.title or "",
            "description": (doc.meta_by_name("description")
                            or doc.meta_by_property("og:description") or "")}


def build(base: str, *, allow_private=False, timeout=20, max_pages=40,
          concurrency=4, obey_robots=True) -> dict:
    root = f"{urlparse(base).scheme}://{urlparse(base).netloc}"
    home = http.fetch(base, allow_private=allow_private, timeout=timeout)
    host = urlparse(home.final_url or base).netloc
    site_name, description = host, ""
    if home.ok:
        hdoc = htmlx.parse(home.text, base_url=home.final_url or base)
        site_name = (hdoc.meta_by_property("og:site_name") or hdoc.title or host)
        description = (hdoc.meta_by_name("description")
                      or hdoc.meta_by_property("og:description") or "")

    robots_txt = http.fetch_text(urljoin(root + "/", "robots.txt"),
                                 allow_private=allow_private, timeout=timeout) or ""
    rt = RobotsTxt.parse(robots_txt)
    candidates = crawl_site.discover(base, allow_private=allow_private,
                                     timeout=timeout, limit=max_pages * 2,
                                     robots_txt=robots_txt)
    urls = []
    for u in candidates:
        if obey_robots and rt.disallowed(u, crawl_site.CRAWLER_AGENT):
            continue
        urls.append(u)
        if len(urls) >= max_pages:
            break

    with ThreadPoolExecutor(max_workers=concurrency) as ex:
        metas = [m for m in ex.map(
            lambda u: _page_meta(u, allow_private, timeout), urls) if m]

    # Drop per-page descriptions that just echo the site-wide description — that's
    # boilerplate, not useful per-link context.
    site_desc = description.strip().lower()
    for m in metas:
        if m["description"].strip().lower() == site_desc:
            m["description"] = ""

    return {"site_name": site_name, "description": description,
            "sections": group_sections(metas), "pages": len(metas)}


def main(argv=None) -> int:
    cfg = configlib.load_from_args(argv)
    d = cfg.defaults
    ap = argparse.ArgumentParser(description="Generate a starter llms.txt",
                                 parents=[configlib.config_arg_parser()])
    ap.add_argument("url", help="site URL")
    ap.add_argument("--max-pages", type=int, default=40,
                    help="max pages to include (default 40)")
    ap.add_argument("--concurrency", type=int, default=d["concurrency"])
    ap.add_argument("--timeout", type=int, default=d["timeout"])
    ap.add_argument("--ignore-robots", action="store_true")
    ap.add_argument("--allow-private", action="store_true")
    ap.add_argument("-o", "--output")
    args = ap.parse_args(argv)

    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

    data = build(args.url, allow_private=args.allow_private, timeout=args.timeout,
                 max_pages=args.max_pages, concurrency=args.concurrency,
                 obey_robots=not args.ignore_robots)
    out = render_llms_txt(data["site_name"], data["description"], data["sections"])
    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(out)
        print(f"Wrote llms.txt ({data['pages']} pages) to {args.output}")
    else:
        print(out)
    print("\n# NOTE: this is a starter — curate it, and treat llms.txt as a "
          "low-cost, low-certainty bet (see references/geo-llmo.md).",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
