"""Offline tests grouped by area; no network or required third-party dependencies."""

try:
    from ._smoke_support import *  # noqa: F401,F403
except ImportError:  # direct discovery with ``-s tests``
    from _smoke_support import *  # type: ignore  # noqa: F401,F403

import audit as audit_mod
from lib import http, links
from lib import report as report_lib
from lib.report import Report, below_threshold


class TestHtmlRenderer(unittest.TestCase):
    def _report(self):
        r = Report("https://x.com/p", final_url="https://x.com/p",
                   fetched_status=200)
        r.add("technical", "critical", "Missing <title>", "No title element.",
              "Add a unique title.", evidence="<head></head>")
        r.add("content", "medium", "Thin content", "Only 120 words.",
              "Expand the copy.")
        r.add("geo", "low", "No llms.txt", "", "Add /llms.txt.")
        r.ok("schema", "JSON-LD present", "Article detected")
        return r

    def test_to_html_is_self_contained_document(self):
        html = self._report().to_html()
        self.assertTrue(html.lstrip().startswith("<!DOCTYPE html>"))
        self.assertIn("</html>", html)
        self.assertIn("<style>", html)          # inline CSS, not linked
        self.assertNotIn("<link", html)          # no external stylesheet
        self.assertNotIn("<script", html)        # no scripts
        self.assertIn("<svg", html)              # score gauge present

    def test_to_html_has_inline_brand_logo(self):
        html = self._report().to_html()
        self.assertIn('<header class="brand">', html)   # branded header
        self.assertIn("data:image/png;base64,", html)   # logo embedded inline...
        self.assertNotIn('src="assets/', html)          # ...not an external file
        self.assertIn("Generated by", html)             # footer credit

    def test_to_html_escapes_untrusted_text(self):
        r = Report("https://x.com/")
        r.add("technical", "high", "Bad <tag> & \"quote\"",
              "Detail with <b>markup</b>", "Fix <it>")
        html = r.to_html()
        self.assertIn("&lt;tag&gt;", html)
        self.assertNotIn("<b>markup</b>", html)  # would be an injection

    def test_to_html_shows_score_and_findings(self):
        html = self._report().to_html()
        self.assertIn("Missing &lt;title&gt;", html)
        self.assertIn("Thin content", html)
        self.assertIn("Priority fixes", html)
        self.assertIn("Passing checks", html)

    def test_md_to_html_covers_our_subset(self):
        md = ("# Title\n\n## Section\n\n| A | B |\n|:--|:--|\n| 1 | `x` |\n\n"
              "- one\n- two\n\n> a note with **bold**\n\n---\n")
        out = report_lib.md_to_html(md)
        for tag in ("<h1>", "<h2>", "<table>", "<th>", "<td>", "<ul>",
                    "<li>", "<blockquote>", "<strong>", "<code>", "<hr>"):
            self.assertIn(tag, out)

    def test_pdf_deliver_falls_back_to_html(self):
        import tempfile
        import contextlib
        import io
        # WeasyPrint isn't a test dependency, so deliver() must gracefully
        # write HTML instead of crashing.
        d = tempfile.mkdtemp()
        pdf = os.path.join(d, "r.pdf")
        with contextlib.redirect_stderr(io.StringIO()), \
                contextlib.redirect_stdout(io.StringIO()):
            rc = report_lib.deliver("pdf", pdf, "<html><body>hi</body></html>",
                                    score=88)
        self.assertEqual(rc, 0)
        self.assertTrue(os.path.exists(pdf) or
                        os.path.exists(os.path.join(d, "r.html")))

    def test_pdf_without_output_is_usage_error(self):
        import contextlib
        import io
        with contextlib.redirect_stderr(io.StringIO()):
            rc = report_lib.deliver("pdf", None, "<html></html>")
        self.assertEqual(rc, 2)

    def test_audit_render_html(self):
        from collections import Counter
        page = self._report()
        data = {
            "site": "https://x.com",
            "page": page,
            "site_result": {
                "base": "https://x.com", "avg_score": 70, "pages_scanned": 2,
                "pages": [{"score": 56, "url": "https://x.com/"},
                          {"score": 84, "url": "https://x.com/a"}],
                "recurring": Counter({("technical", "high", "No meta description"): 2}),
                "links": {"broken": [], "checked": 8, "skipped_over_cap": 0},
                "duplicates": [],
            },
            "sitemap": {"start": "https://x.com", "seeds": []},
        }
        html = audit_mod.render_html(data)
        self.assertTrue(html.lstrip().startswith("<!DOCTYPE html>"))
        self.assertIn("Homepage audit", html)
        self.assertIn("Site-wide", html)
        self.assertIn("Sitemap", html)
        self.assertIn("<svg", html)

class TestScanDiff(unittest.TestCase):
    def setUp(self):
        import diff_scan
        self.diff = diff_scan

    def _report(self, findings, score_url="https://x.com/p"):
        r = Report(score_url, final_url=score_url, fetched_status=200)
        for cat, sev, title in findings:
            r.add(cat, sev, title)
        import json
        return json.loads(r.to_json())

    def test_added_resolved_and_score_delta(self):
        old = self._report([("technical", "critical", "Canonical points elsewhere"),
                            ("technical", "high", "Meta description missing")])
        new = self._report([("technical", "high", "Meta description missing"),
                            ("schema", "critical", "Broken JSON-LD")])
        d = self.diff.diff_reports(old, new)
        self.assertEqual([f["title"] for f in d["added"]], ["Broken JSON-LD"])
        self.assertEqual([f["title"] for f in d["resolved"]], ["Canonical points elsewhere"])
        self.assertEqual(d["unchanged"], 1)
        self.assertTrue(d["regression"])          # new critical finding
        self.assertEqual([f["title"] for f in d["new_critical_high"]], ["Broken JSON-LD"])

    def test_dynamic_title_suffix_matches_across_runs(self):
        # "Thin content (210 words)" and "(95 words)" are the same finding.
        old = self._report([("content", "medium", "Thin content (210 words)")])
        new = self._report([("content", "high", "Thin content (95 words)")])
        d = self.diff.diff_reports(old, new)
        self.assertEqual(d["added"], [])
        self.assertEqual(d["resolved"], [])
        self.assertEqual(len(d["worsened"]), 1)
        self.assertEqual(d["worsened"][0]["from"], "medium")
        self.assertEqual(d["worsened"][0]["to"], "high")

    def test_improvement_is_not_a_regression(self):
        old = self._report([("technical", "high", "Meta description missing")])
        new = self._report([])
        d = self.diff.diff_reports(old, new)
        self.assertFalse(d["regression"])
        self.assertEqual(len(d["resolved"]), 1)
        self.assertIn("Improved", self.diff._verdict(d))

    def test_regression_on_score_drop_without_new_high(self):
        old = self._report([("geo", "low", "No llms.txt")])
        new = self._report([("geo", "low", "No llms.txt"),
                            ("content", "medium", "Thin content")])
        d = self.diff.diff_reports(old, new)
        self.assertTrue(d["regression"])          # score dropped (added medium)
        self.assertEqual(d["new_critical_high"], [])

    def test_accepts_audit_shape_json(self):
        old = {"site": "https://x.com", "overall_score": 60,
               "homepage": {"url": "https://x.com", "score": 60,
                            "findings": [{"category": "technical",
                                          "severity": "high",
                                          "title": "Meta description missing"}]}}
        new = {"site": "https://x.com", "overall_score": 72,
               "homepage": {"url": "https://x.com", "score": 72, "findings": []}}
        d = self.diff.diff_reports(old, new)
        self.assertEqual(d["score_delta"], 12)
        self.assertEqual(len(d["resolved"]), 1)

    def test_unrecognized_json_raises(self):
        with self.assertRaises(ValueError):
            self.diff._normalize({"nope": 1})

    def test_render_markdown_smoke(self):
        old = self._report([("technical", "high", "Meta description missing")])
        new = self._report([("schema", "critical", "Broken JSON-LD")])
        md = self.diff.render_markdown(self.diff.diff_reports(old, new))
        self.assertIn("Narwhal Scan Diff", md)
        self.assertIn("New findings", md)
        self.assertIn("Resolved", md)

class TestRenderReport(unittest.TestCase):
    def setUp(self):
        import render_report
        self.rr = render_report

    def test_renders_branded_self_contained_html(self):
        html = self.rr.render("# My Audit\n\nSome **bold** text.", subtitle="https://x.com")
        self.assertTrue(html.lstrip().startswith("<!DOCTYPE html>"))
        self.assertIn('<header class="brand">', html)          # branded
        self.assertIn("data:image/png;base64,", html)          # inline logo
        self.assertIn("<strong>bold</strong>", html)
        self.assertNotIn("<script", html)

    def test_first_h1_becomes_title_and_leaves_body(self):
        html = self.rr.render("# Narwhal Site Audit\n\n## Summary\n\nBody.")
        self.assertIn("Narwhal Site Audit", html)              # used as the title
        self.assertNotIn("# Narwhal Site Audit", html)          # H1 removed from body
        self.assertIn("<h2>Summary</h2>", html)                 # rest of body intact

    def test_explicit_title_overrides(self):
        html = self.rr.render("# Ignored\n\nBody.", title="Custom Title")
        self.assertIn("Custom Title", html)

    def test_markdown_links_render(self):
        html = self.rr.render("See [the docs](https://example.com/docs).")
        self.assertIn('<a href="https://example.com/docs">the docs</a>', html)

class TestRenderHardening(unittest.TestCase):
    def test_missing_browser_gives_actionable_hint(self):
        # Playwright installed but Chromium binary absent — the message must tell
        # the user exactly how to fix it, not surface a raw stack string.
        msg = http._browser_launch_hint(
            Exception("Executable doesn't exist at /home/.cache/ms-playwright/..."))
        self.assertIn("playwright install chromium", msg)

    def test_generic_render_error_is_labelled(self):
        msg = http._browser_launch_hint(Exception("some other failure"))
        self.assertIn("Playwright render failed", msg)
        self.assertIn("some other failure", msg)

    def test_chromium_pdf_backend_absent_is_graceful(self):
        # Without Playwright installed, the Chromium backend must return False
        # (not raise), so pdf_from_html can fall through to the HTML fallback.
        try:
            import playwright  # noqa: F401
            self.skipTest("Playwright installed; can't test the absent path")
        except ImportError:
            self.assertFalse(report_lib._pdf_via_chromium("<html></html>", "x.pdf"))

    def test_pdf_from_html_survives_missing_native_libs(self):
        # Simulate WeasyPrint present but its native libs missing (OSError on
        # import) — pdf_from_html must return False, not raise.
        import builtins
        real_import = builtins.__import__

        def fake_import(name, *a, **k):
            if name == "weasyprint":
                raise OSError("cannot load library 'libgobject-2.0-0'")
            return real_import(name, *a, **k)

        builtins.__import__ = fake_import
        try:
            self.assertFalse(report_lib.pdf_from_html("<html></html>", "x.pdf"))
        finally:
            builtins.__import__ = real_import

class TestFailUnderGate(unittest.TestCase):
    def test_no_threshold_never_fails(self):
        self.assertFalse(below_threshold(0, None))
        self.assertFalse(below_threshold(100, None))

    def test_below_threshold_fails(self):
        self.assertTrue(below_threshold(57, 80))

    def test_at_or_above_threshold_passes(self):
        self.assertFalse(below_threshold(80, 80))
        self.assertFalse(below_threshold(95, 80))

    def test_works_with_float_average(self):
        self.assertTrue(below_threshold(79.5, 80))
        self.assertFalse(below_threshold(80.0, 80))
